name: CI Pipeline with Pytest and Docker Hub Deployment

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Run the tests
  test:
    name: Run Pytest Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests with pytest
        run: pytest

  # Job 2: Build and push the Docker image
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: test 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest 
